site_name: Botanyhelp
pages:
- Home: 'index.md'
- Linux:
    - 'Clustering': 'linux/clustering.md'
    - 'Amazon': 'linux/amazon.md'
    - 'Heroku': 'linux/heroku.md'
    - 'Google App Engine': 'linux/gae.md'
- Software:
    - 'Android': 'software/android.md'
    - 'Python': 'software/python.md'
    - 'Java': 'software/java.md'
    - 'Javascript': 'software/javascript.md'
    - 'R': 'software/r.md'
    - 'Ruby': 'software/ruby.md'
    - 'Perl': 'software/perl.md'
    - 'Php': 'software/php.md'
    - 'Content': 'software/content.md'
    - 'C': 'software/c.md'
    - 'Ios': 'software/ios.md'
- Databases:
    - 'Mysql': 'databases/mysql.md'
    - 'Postgres': 'databases/postgres.md'
    - 'Sqlite': 'databases/sqlite.md'
    - 'Google_data_store': 'databases/google_data_store.md'
- Experience:
    - 'Experience': 'experience/experience.md'
    - 'Certificates': 'experience/certificates.md'
